/*	Copyright (c) 1990, 1991, 1992, 1993, 1994 Novell, Inc. All Rights Reserved.	*/
/*	Copyright (c) 1993 Novell, Inc. All Rights Reserved.	*/
/*	  All Rights Reserved  	*/

/*	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF Novell Inc.	*/
/*	The copyright notice above does not evidence any   	*/
/*	actual or intended publication of such source code.	*/

/*#   Copyright (c) 1990, 1991, 1992, 1993 Novell, Inc. All Rights Reserved.
#   Copyright (c) 1993 Novell, Inc. All Rights Reserved.
#     All Rights Reserved

#   THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF Novell Inc.
#   The copyright notice above does not evidence any
#   actual or intended publication of such source code.
*/

#ident	"@(#)setpass:nwerrormap.h	1.1"
#ident	"$Header: $"


#ifndef	_NWERRORMAP_H
#define	_NWERRORMAP_H

#include <nwapi.h>
#include <nwerrors.h>

#define ACCOUNT_DISABLED				NWERR_ACCOUNT_DISABLED
#define BINDERY_ACCESS_ERROR			NWERR_SERVER_BINDERY_LOCKED
/*#define SERVER_BINDERY_LOCKED			NWERR_CONN_BINDERY_SECURITY*/
/*#define INTRUDER_DETECTION_LOCK			NWERR_LOGIN_LOGOUT*/
#define LOGIN_DENIED_NO_ACCOUNT_BALANCE	NWERR_NO_ACCOUNT_BALANCE
#define LOGIN_DENIED_NO_CONNECTION		NWERR_MAXIMUM_LOGINS_EXCEEDED
#define LOGIN_DENIED_NO_CREDIT			NWERR_CREDIT_LIMIT_EXCEEDED
#define NO_FREE_CONNECTION_SLOTS		0x00F9
#define CONNECTION_TABLE_FULL			0x0004
#define NO_MORE_SERVER_SLOTS			NWERR_NO_MORE_SERVER_SLOTS
#define NO_RESPONSE_FROM_SERVER			NWERR_NO_RESPONSE_FROM_SERVER
#define NO_SUCH_OBJECT					NWERR_NO_SUCH_OBJECT
#define PASSWORD_HAS_EXPIRED_NO_GRACE	NWERR_PASSWORD_HAS_EXPIRED_NO_GRACE
#define SUPERVISOR_HAS_DISABLED_LOGIN	NWERR_SUPERVISOR_HAS_DISABLED_LOGIN
#define UNAUTHORIZED_LOGIN_STATION		NWERR_UNAUTHORIZED_LOGIN_STATION
#define UNAUTHORIZED_LOGIN_TIME			NWERR_UNAUTHORIZED_LOGIN_TIME
/*#define NO_RESPONSE_FROM_SERVER			NWERR_CONN_UNKNOWN_FILE_SERVER*/
#define SERVER_BINDERY_LOCKED			NWERR_SERVER_BINDERY_LOCKED
#define PASSWORD_TOO_SHORT				NWERR_PASSWORD_TOO_SHORT
#define PASSWORD_NOT_UNIQUE				NWERR_PASSWORD_NOT_UNIQUE
#define INTRUDER_DETECTION_LOCK			NWERR_INTRUDER_DETECTION_LOCK
#define NO_SUCH_OBJECT_OR_BAD_PASSWORD	NWERR_NO_SUCH_OBJECT_OR_BAD_PASSWORD
#define PASSWORD_HAS_EXPIRED			NWERR_OLD_PASSWORD
#define	INVALID_CONNECTION				NWERR_INVALID_CONNECTION_ID
#define	ERR_CONN_NOT_LOGGED_IN			0x897D	/*125*/

#endif	_NWERRORMAP_H
