#pragma ident	"@(#)s364:s364/devices/makefile.stdenv	1.2"
#	NAME
#
#		makefile : Make file.
#
#	SYNOPSIS
#
#	DESCRIPTION
#
#	RETURNS
#
#	ENVIRONMENT VARIABLES
#
#	FILES
#
#	SEE ALSO
#
#	CAVEATS
#
#	BUGS
#
#	AUTHORS
#
#	HISTORY
#

#	AM directives.

..source  : s364.vinfo Imakefile
..include : s364_init

#	Standard make include file.

include ${std_make_include_file}
