#4: X, newed on line `prog7.c`34 (size 4 at -----)
#5: char[13], newed on line `prog7.c`25 (size 1 at -----)
---------------------
#7: X, newed on line `prog7.c`34 (size 4 at -----)
#8: char[13], newed on line `prog7.c`25 (size 1 at -----)
---------------------
#9: X, newed on line `prog7.c`34 (size 4 at -----)
#10: char[13], newed on line `prog7.c`25 (size 1 at -----)
---------------------
#11: X, newed on line `prog7.c`34 (size 4 at -----)
#12: char[13], newed on line `prog7.c`25 (size 1 at -----)
---------------------
