#0: ? (size 64 at -----), alert!
#1: ? (size 64 at -----), alert!
#2: ? (size 64 at -----), alert!
#3: ? (size 64 at -----), alert!
#4: X, newed on line `prog6.c`34 (size 4 at -----)
#5: char[13], newed on line `prog6.c`25 (size 1 at -----)
#6: X, newed on line `prog6.c`34 (size 4 at -----)
#7: char[13], newed on line `prog6.c`25 (size 1 at -----)
#8: X, newed on line `prog6.c`34 (size 4 at -----)
#9: char[13], newed on line `prog6.c`25 (size 1 at -----)
#10: X, newed on line `prog6.c`34 (size 4 at -----)
#11: char[13], newed on line `prog6.c`25 (size 1 at -----)
