1 Error
2 Espere, por favor
3 Buscando la librería...
4 El módulo de consultas de bibliotecas no puede arrancar. Es posible que no esté instalado.
5 Enlace de ayuda mal construido.
6 Depuración: Se ha especificado una opción de línea de comando errónea.
7 Enlace de ayuda mal construido: demasiados argumentos.
8 El libro %s no está instalado en su sistema.
9 No tiene permiso para leer el libro %s.
10 El capítulo y sección referenciados no pueden encontrarse en la biblioteca.
11 Un archivo de datos interno del módulo de consultas de bibliotecas no puede leerse.
12 El módulo de consultas de biblioteca principal no puede abrirse.
13 Error interno de programa: no se puede inicializar la función de devolución de llamada.
14 El observador de documentación no está instalado en su sistema.
15 No se encuentra la colección de libros %s.
