1 Erreur
2 Veuillez patienter
3 Recherche de la bibliothèque...
4 Impossible de lancer le parcoureur de bibliothèque, il se peut qu'il ne soit pas installé.
5 Lien avec l'aide établi de façon impropre.
6 Débogage : option incorrecte spécifiée au niveau de la ligne de commande.
7 Lien avec l'aide établi de façon impropre : arguments trop nombreux.
8 Le manuel %s n'est pas installé sur votre système.
9 Vous n'êtes pas autorisé à lire le manuel %s.
10 Il est impossible de trouver le chapitre et la section référencés dans cette bibliothèque.
11 Un des fichiers de données du programme de lecture de la bibliothèque interne ne peut être lu.
12 Il est impossible d'ouvrir le programme de lecture principal de la bibliothèque.
13 Erreur de programme interne : impossible d'initialiser la fonction callback.
14 Le programme de lecture de la documentation n'est pas installé sur votre système.
15 Série de manuels %s introuvable.
