/*	Copyright (c) 1990, 1991, 1992, 1993, 1994 Novell, Inc. All Rights Reserved.	*/
/*	Copyright (c) 1993 Novell, Inc. All Rights Reserved.	*/
/*	  All Rights Reserved  	*/

/*	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF Novell Inc.	*/
/*	The copyright notice above does not evidence any   	*/
/*	actual or intended publication of such source code.	*/

#ident	"@(#)remapps:msgs.h	1.3"

/*--------------------------------------------------------------------
** Filename : msgs.h
**
** Description : This header file contains all the internationalized
**               strings
**------------------------------------------------------------------*/

#ifndef    FS
#define    FS      "\001"
#endif

/*--------------------------------------------------------------------
**          H E L P   S E C T I O N   N U M B E R S  
**------------------------------------------------------------------*/
#define    HELP_SECT_TAG_10        "10"
#define    HELP_SECT_TAG_30        "30"

/*--------------------------------------------------------------------
**          I N T E R N A T I O N A L I Z A T I O N 
**------------------------------------------------------------------*/

#define    TXT_TITLE         "remappl:1" FS "Remote_Applications"
#define    TXT_ICON_NAME     "remappl:2" FS "Remote Apps"
#define    TXT_SERVER_LABEL  "remappl:3" FS "Servers with Applications"
#define    TXT_SERVICE_LABEL "remappl:4" FS "Remote Applications"
#define    TXT_EXTRA_LABEL   "remappl:5" FS "NULL" 
#define    TXT_LAUNCH        "remappl:6" FS "Open"
#define    TXT_M_LAUNCH      "remappl:7" FS "O"
#define    TXT_MAKE_ICON     "remappl:8" FS "Make Icon"
#define    TXT_M_MAKE_ICON   "remappl:9" FS "M"
#define    TXT_CANCEL        "remappl:10" FS "Cancel"
#define    TXT_M_CANCEL      "remappl:11" FS "C"
#define    TXT_HELP          "remappl:12" FS "Help" 
#define    TXT_M_HELP        "remappl:13" FS "H"
#define    TXT_LAUNCH_MESS   "remappl:14" FS "%s should open in one to three minutes"
#define    TXT_SEL_APPL      "remappl:15" FS "You must first select an application"
#define   TXT_SERVICE_LABEL2 "remappl:16" FS "Remote Applications on %s"
#define   TXT_QUERY_MESS     "remappl:17" FS "Querying %s for Remote Applications"
#define   TXT_OUT_OF_MEM     "remappl:18" FS "There is insufficient memory to continue execution of this program. Press enter to Exit"

/*--------------------------------------------------------------------
**  S T R I N G S    F O R    A U T H    W I N D O W
**------------------------------------------------------------------*/
#define   TXT_AUTH_TITLE     "remappl:19" FS "Authentication"
#define   TXT_AUTH_TXT       "remappl:20" FS "Enter your user ID and password for remote system %s"
#define   TXT_USER_ID        "remappl:21" FS "Login ID"
#define   TXT_M_USER_ID      "remappl:22" FS "L"
#define   TXT_PASSWD         "remappl:23" FS "Password"
#define   TXT_M_PASSWD       "remappl:24" FS "P"
#define   TXT_LOGIN_FOOTER   "remappl:25" FS "Password entry will not be displayed as you type it."
#define    TXT_LOGIN         "remappl:26" FS "Authenticate"
#define    TXT_M_LOGIN       "remappl:27" FS "A"
#define    TXT_RESET         "remappl:28" FS "Reset"
#define    TXT_M_RESET       "remappl:29" FS "R"
#define    TXT_LOG_CANCEL    "remappl:30" FS "Cancel"
#define    TXT_M_LOG_CANCEL  "remappl:31" FS "C"
#define    TXT_LOG_HELP      "remappl:32" FS "Help" 
#define    TXT_M_LOG_HELP    "remappl:33" FS "H"


#define    TXT_NO_SERVERS    "remappl:34" FS "There are no UnixWare servers with applications on the network."
#define    TXT_OK_BUTTON     "remappl:35" FS "OK"
#define    TXT_M_OK_BUTTON   "remappl:36" FS "O"

#define    TXT_UNABLE_TO_CONNECT "remappl:37" FS "Unable to connect to %s"
#define    TXT_DO_NOT_EDIT   "remappl:38" FS "# DO NOT EDIT THIS FILE.\n"
#define    TXT_CANT_CREATE_ICON  "remappl:39" FS "Unable to create icon"
#define    TXT_CANT_GET_XNAME    "remappl:40" FS "Unable to get xhost name"
#define    TXT_NO_APPLICATIONS   "remappl:41" FS "No Applications are available on %s"
#define    TXT_MKICON_MESS       "remappl:42" FS "An icon has been created for %s"
#define    TXT_SECT_TAG_10        "remappl:43" FS "10"
#define    TXT_SECT_TAG_70        "remappl:44" FS "70"
#define    TXT_INVALID_CONFIG     "remappl:45" FS "Cannot execute application.\n Your machine is not properly configured for networking."
#define    TXT_NETWORK_ERROR      "remappl:46" FS "A network error occurred while performing this function"
#define    TXT_NOT_SAPPING        "remappl:47" FS "To execute this application you must first execute NetWare_Setup and turn peer-to-peer on."
#define    TXT_CANT_CHDIR         "remappl:48" FS "Unable to change to /tmp directory"
#define    TXT_TITLE_DAY1    "remappl:49" FS "Remote_Apps"
#define    TXT_ICON_NAME_DAY1 "remappl:50" FS "Remote_Apps"

