/*	Copyright (c) 1990, 1991, 1992, 1993, 1994 Novell, Inc. All Rights Reserved.	*/
/*	Copyright (c) 1993 Novell, Inc. All Rights Reserved.	*/
/*	  All Rights Reserved  	*/

/*	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF Novell Inc.	*/
/*	The copyright notice above does not evidence any   	*/
/*	actual or intended publication of such source code.	*/

#pragma	ident	"@(#)xidleprefs:main.c	1.2"
/*
 * Generated by the ICS Application Builder (xab).
 *
 *
 * Application Builder 2.5 Beta.
 *
 */
/*
 * Required Olit Include Files
 */
#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#include <Xol/OpenLook.h>
#include <X11/Shell.h>
#include <xidleprefs.h>
#include <locale.h>

/*
 * Forward routine declarations.
 */
Widget CreatepopupWindowShell();

/*
 * Widget variable declarations.
 */
Widget AppShell; 
Widget PopupWindowShell;
static void	PopdownCB (Widget, XtPointer, XtPointer);


/*
 *	Xidlelock Preference Resources that we need to pick up
 */
static XtResource Xidlelockresources[] = {
	{	"notify", "Notify",XtRBoolean, sizeof(Boolean),
		XtOffset(XidlelockApplicationDataPtr,notify), XtRString, "true"
	},
	{	"locker", "Locker",XtRString, sizeof(char *),
		XtOffset(XidlelockApplicationDataPtr,locker), XtRString, 
		"/usr/X/bin/xlock"
	},
	{	"timeout", "Timeout",XtRInt, sizeof(int),
		XtOffset(XidlelockApplicationDataPtr, timeout), XtRImmediate, 
		(XtPointer)0 
	},
};
/*
 *	XLock Preference Resources that we need to pick up
 */

static XtResource XLockresources[] = {
	{	"mode", "Mode",XtRString, sizeof(char *),
		XtOffset(XLockApplicationDataPtr,mode), XtRString, "hop"
	},
	{	"nolock", "Nolock",XtRBoolean, sizeof(Boolean),
		XtOffset(XLockApplicationDataPtr,nolock), XtRString, "false"
	},
	{	"enablesaver", "Enablesaver",XtRBoolean, sizeof(Boolean),
		XtOffset(XLockApplicationDataPtr, enablesaver),
		XtRString, "false" 
	},
};

XidlelockApplicationData	Xidlelockdata;
XLockApplicationData	XLockdata;
Display*  dp; 
XtAppContext	app_con;

/*
 * Main Program.
 */

main(argc, argv)
int argc;
char **argv;
{
    Widget	XLock;
    Widget	Xidlelock;
    Window	otherWindow;

    setlocale (LC_ALL, "");

    OlToolkitInitialize(&argc, argv, (XtPointer)NULL);
	/*
	 * Use xidlelock so that we it's defaults
	 */
    AppShell = XtAppInitialize (&app_con, "xidlelock", NULL,
					 				0, &argc, argv, NULL, NULL,0);

	DtInitialize (AppShell); 

    if (argc != 1) 
	{
		/* 	
		* Creates an error window to display this
	  	*/
		EXIT_CODE=TRUE;
		Error (AppShell, GetStr (TXT_argError));
		XtAppMainLoop(app_con);
		exit(1);				/* NOT REACHED */
	}

	dp = XtDisplay(AppShell);

	XtGetApplicationResources(AppShell, &Xidlelockdata, Xidlelockresources,
								XtNumber(Xidlelockresources), NULL,0 );

	XLock = XtAppCreateShell(NULL, "xlock",applicationShellWidgetClass,
														dp,NULL,0);
	XtGetApplicationResources(XLock, &XLockdata, XLockresources,
								XtNumber(XLockresources), NULL,0 );

	XtDestroyWidget(XLock);

    PopupWindowShell = CreatepopupWindowShell(AppShell);
    XtAddCallback (PopupWindowShell, XtNpopdownCallback, PopdownCB, (XtPointer)0);

        /*
	 * Only allow one instance to be active,  raise the active
	 * one to the surface if there is one.
	 * Need to realize it first, XtWindow will return 0 otherwise, no
	 * window number assigned until realized.
	 */
    XtRealizeWidget (PopupWindowShell);
    otherWindow =DtSetAppId (dp, XtWindow (PopupWindowShell),GetStr(TXT_title));

    if (otherWindow != None)
    {
	XMapWindow (dp, otherWindow);
	XRaiseWindow (dp, otherWindow);
	/*
	 * Seems like the right thing to do.  Wouldn't have clicked
	 * on the icon if he didn't want focus given to the application
	 * window.
	 */
	XSetInputFocus(dp,otherWindow,RevertToNone,CurrentTime);
	XFlush (dp);
	exit (0);
    }
    
    XtPopup(PopupWindowShell, XtGrabNone);


	XtAppMainLoop(app_con);
}
/* PopdownCB
 *
 * Popdown callback.  Mark the property sheet as unposted.
 */
static void
PopdownCB (Widget widget, XtPointer client_data, XtPointer call_data)
{
	XtDestroyWidget (widget);
	exit (0);
}       /* End of PopdownCB () */

