/*	Copyright (c) 1990, 1991, 1992, 1993, 1994 Novell, Inc. All Rights Reserved.	*/
/*	Copyright (c) 1993 Novell, Inc. All Rights Reserved.	*/
/*	  All Rights Reserved  	*/

/*	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF Novell Inc.	*/
/*	The copyright notice above does not evidence any   	*/
/*	actual or intended publication of such source code.	*/

#ifndef NOIDENT
#pragma ident	"@(#)dtadmin:userad/login_msgs.h	1.27.1.16"
#endif
/*
 * This file contains all the message strings for the Desktop UNIX
 * dtadmin client dtuser.
 * 
 */

#define	string_appName 	"dtuser:1" FS "User Setup"
#define	string_iconName "dtuser:2" FS "User Setup"
#define	string_badGroup "dtuser:3" FS "Nonexistent group; select another\n\n"
#define	string_badShell	"dtuser:4" FS "Shell not executable by user:  "
#define	string_malloc	"dtuser:5" FS "Operation failed due to lack of memory"
#define	string_permfile	"dtuser:6" FS "Unable to read permissions table"
#define	string_adm	"dtuser:7" FS "Unable to add user to admin database"
#define	string_noChange	"dtuser:8" FS "User account %s was left unchanged"
#define	string_propLine	"dtuser:9" FS "User Setup: User Account Properties"
#define	string_sysLine	"dtuser:10" FS "User Setup: Reserved Account Properties"
#define	string_groupLine	"dtuser:11" FS "User Setup: Group Properties"
#define	string_addUserLine	"dtuser:12" FS "User Setup: Add New User Account"
#define	string_addSysLine	"dtuser:13" FS "User Setup: Add New Reserved Account"
#define	string_addGroupLine	"dtuser:14" FS "User Setup: Add New Group"
#define	string_permLine	"dtuser:15" FS "User Setup: User Permissions"
#define	string_errLine	"dtuser:16" FS "User Setup: Error"
#define	string_confLine	"dtuser:17" FS "User Setup: Confirmation"
#define	string_userBaseLine	"dtuser:18" FS "User Setup: User Accounts"
#define	string_sysBaseLine	"dtuser:19" FS "User Setup: Reserved Accounts"
#define	string_groupBaseLine	"dtuser:20" FS "User Setup: Groups"

#define	string_noPerms	"dtuser:21" FS "you are not authorized to %s %ss"
#define	string_inUse	"dtuser:22" FS "cannot %s %s %s while in use"
#define	string_dupl	"dtuser:23" FS "%s would duplicate an existing %s"
#define	string_badDir	"dtuser:24" FS "cannot %s home directory for %s %s"
#define	string_unknown	"dtuser:25" FS "%s %s %s: unrecognized error"
#define	string_shellRequired	"dtuser:26" FS "Please fill in the \"Shell\" field"
#define	string_deleteFiles	"dtuser:27" FS "Permamently delete all files and folders in %s?  Are you sure?"
#define	string_backupErrs	"dtuser:28" FS "Errors occured while backing up %s's files. Do you still want to permamently delete all files and folders in %s?"
#define	string_notBackedUp	"dtuser:29" FS "%s's files were not backed up.  Do you still want to permamently delete all files and folders in %s?"

#define	format_noSelectFmt	"dtuser:31" FS "no %s has been selected"
#define	format_applyFmt		"dtuser:32" FS "%s %s %s %s"
#define	format_syntaxFmt	"dtuser:33" FS "invalid character '%c' in %s %s\n\n"
#define	format_noIdFmt	 	"dtuser:34" FS "%s field required\n\n"
#define	format_maxIdFmt	 	"dtuser:35" FS "%s must not be larger than %d\n\n"
#define	format_reuseFmt		"dtuser:36" FS "\n\n(Reuse existing %s %d?)"
#define	format_permFmt		"dtuser:37" FS "permission change for user %s%s"
#define	format_ownerFmt		"dtuser:38" FS "%s %s %s %s%s"
#define	format_ageIdFmt	 	"dtuser:39" FS "%s %s was previously used. You may not re-use it yet. It has not \"aged\" long enough.\n\n"
#define	format_inUse	 	"dtuser:40" FS "%s %s already in use; choose another\n\n"

#define	label_edit		"dtuser:41" FS "Account"
#define	label_view		"dtuser:42" FS "View"
#define	label_help		"dtuser:43" FS "Help"
#define	label_new		"dtuser:44" FS "New..."
#define	label_delete		"dtuser:45" FS "Delete"
#define	label_users		"dtuser:46" FS "Users"
#define	label_sysaccts		"dtuser:47" FS "Reserved"
#define	label_groups		"dtuser:48" FS "Groups"
#define	label_glist		"dtuser:411" FS "Groups:"
#define	label_apply		"dtuser:50" FS "Apply"
#define	label_reset		"dtuser:51" FS "Reset"
#define	label_cancel		"dtuser:52" FS "Cancel"
#define	label_prop		"dtuser:53" FS "Properties..."
#define	label_perm		"dtuser:54" FS "Permissions..."
#define	label_yes		"dtuser:55" FS "Yes"
#define	label_no		"dtuser:56" FS "No"
#define	label_OK		"dtuser:57" FS "Continue"
#define	label_desktop		"dtuser:58" FS "Desktop"
#define	label_nondesk		"dtuser:59" FS "Nondesktop"
#define	label_ol		"dtuser:60" FS "OPEN LOOK"
#define	label_motif		"dtuser:61" FS "MOTIF"
#define	label_remove		"dtuser:62" FS "Remove User's Files:"
#define	label_bkup		"dtuser:63" FS "Backup User's Files:"

#define	label_login		"dtuser:64" FS "Login ID:"
#define	label_desc		"dtuser:65" FS "Comment:"
#define	label_uid		"dtuser:66" FS "       User ID:"
#define	label_home		"dtuser:67" FS "       Home Folder:"
#define	label_shell		"dtuser:68" FS "       Shell:"
#define	label_selection		"dtuser:412" FS "Selection:"
#define	label_gname		"dtuser:70" FS "Group Name:"
#define	label_gid		"dtuser:71" FS "Group ID Number:"
#define	label_type		"dtuser:72" FS "Type:"
#define	label_GUI		"dtuser:73" FS "GUI:"
#define	label_extra		"dtuser:413" FS "Show Other Options:"
#define	label_remote		"dtuser:414" FS "X-terminal Name:"
#define	label_owner_acct	"dtuser:76" FS "Selected User is the System Owner"
#define label_add		"dtuser:77" FS "Add"
#define label_user_may		"dtuser:78" FS "Selected User May:"
#define label_locales		"dtuser:79" FS "Locales:"

#define	mnemonic_edit		"dtuser:80" FS "t"
#define	mnemonic_view		"dtuser:81" FS "V"
#define	mnemonic_help		"dtuser:82" FS "H"
#define	mnemonic_new		"dtuser:83" FS "N"
#define	mnemonic_delete		"dtuser:84" FS "D"
#define	mnemonic_users		"dtuser:85" FS "U"
#define	mnemonic_sysaccts	"dtuser:86" FS "D"
#define	mnemonic_groups		"dtuser:87" FS "G"
#define	mnemonic_glist		"dtuser:88" FS "F"
#define	mnemonic_apply		"dtuser:89" FS "A"
#define	mnemonic_reset		"dtuser:90" FS "R"
#define	mnemonic_cancel		"dtuser:91" FS "C"
#define	mnemonic_prop		"dtuser:92" FS "P"
#define	mnemonic_perm		"dtuser:93" FS "e"
#define	mnemonic_desktop	"dtuser:94" FS "K"
#define	mnemonic_nondesk	"dtuser:95" FS "N"
#define	mnemonic_yes		"dtuser:96" FS "Y"
#define	mnemonic_no		"dtuser:97" FS "N"
#define	mnemonic_OK		"dtuser:98" FS "C"
#define	mnemonic_ol		"dtuser:99" FS "O"
#define	mnemonic_motif		"dtuser:100" FS "M"
#define	mnemonic_remove		"dtuser:101" FS "E"
#define	mnemonic_bkup		"dtuser:102" FS "B"
#define	mnemonic_owner_acct	"dtuser:103" FS "O"
#define	mnemonic_add		"dtuser:104" FS "A"
#define	mnemonic_action		"dtuser:105" FS "A"
#define	mnemonic_exit		"dtuser:106" FS "X"
#define	mnemonic_groupBtn	"dtuser:107" FS "G"

#define	label_action		"dtuser:121" FS "Actions"
#define	label_exit		"dtuser:122" FS "Exit"
#define	label_groupBtn		"dtuser:123" FS "Group"

#define label_ok                "dtuser:124" FS "OK"
#define mnemonic_ok             "dtuser:108" FS "O"
#define	label_nis_user		"dtuser:125" FS "Manage User Info via NIS"
#define	label_nis_group		"dtuser:126" FS "Manage Group Info via NIS"

#define	tag_addOp	"dtuser:150" FS "create"
#define	tag_chgOp	"dtuser:151" FS "modify"
#define	tag_delOp	"dtuser:152" FS "delete"
#define	tag_login	"dtuser:153" FS "user account"
#define	tag_desktop	"dtuser:154" FS "desktop environment"
#define	tag_group	"dtuser:155" FS "group"
#define	tag_good	"dtuser:156" FS " - succeeded"
#define	tag_bad		"dtuser:157" FS " - failed"
#define	tag_null	"dtuser:158" FS " - unchanged"
#define	tag_xferOp	"dtuser:159" FS "ownership"
#define	tag_query	"dtuser:160" FS "?"
#define tag_sys		"dtuser:161" FS "reserved account"   
#define tag_account	"dtuser:162" FS "user or reserved account"   

/* Help */

#define	label_intro		"dtuser:200" FS "User Setup..."
#define	label_toc		"dtuser:201" FS "Table of Contents..."
#define	label_hlpdsk		"dtuser:202" FS "Help Desk..."

#define	mnemonic_intro		"dtuser:205" FS "U"
#define	mnemonic_toc		"dtuser:206" FS "T"
#define	mnemonic_hlpdsk		"dtuser:207" FS "K"

#define	help_intro		"10"
#define	help_props		"30"
#define	help_groups		"70"
#define	help_perms		"90"

#define	format_changeOwner	"dtuser:301" FS "%s %s%s"
#define tag_addOwner		"dtuser:302" FS "add ownership to"
#define tag_delOwner		"dtuser:303" FS "remove ownership from"
#define	label_Uid		"dtuser:304" FS "User ID:"
#define	label_Home		"dtuser:305" FS "Home Folder:"
#define	label_Shell		"dtuser:306" FS "Shell:"

#define label_owner_id		"dtuser:400" FS "Account %s has Owner privileges"
#define mnemonic_owner_id	"dtuser:401" FS "w"
#define string_user_may		"dtuser:402" FS "Account %s may:"
#define format_noaccessFmt	"dtuser:403" FS "User %s cannot access %s %s. Select another Folder\n"
#define format_sharehomeFmt	"dtuser:404" FS "\n\n(Reuse existing %s %s?)"

#define format_lastOwnerAccFmt	"dtuser:405" FS "You cannot delete the only owner < %s > of the system.\n To Fix: Select a user to be the new owner then select Permissions from the Actions Menu and give the user ownership.\n" 
#define format_rmLastOwnerFmt	"dtuser:406" FS "You are attempting to remove the only owner < %s > of the system. Give ownership to another user first.\n"

#define string_passwdTitle	"dtuser:407" FS "Password Manager"
#define string_AmericanEng	"dtuser:415" FS "Default (C locale)"
#define string_XdefMoveFailed	"dtuser:408" FS "Unable to move user's .Xdefaults file"
#define string_profMoveFailed	"dtuser:409" FS "Unable to move user's .profile file"
#define string_loginMoveFailed	"dtuser:410" FS "Unable to move user's .login file"
#define string_noNis		"dtuser:416" FS "NIS is unavailable."
#define string_noGroupValues		"dtuser:417" FS "Certain values will be taken from the NIS map."
#define string_noUserValues		"dtuser:418" FS "Certain values will be taken from the NIS map."
#define	format_syntaxFmt2	"dtuser:419" FS "The first character cannot be '%c' in %s %s\n\n"
#define	string_warnLine	"dtuser:420" FS "User Setup: NIS Message"
#define string_notFound		"dtuser:421" FS "%s not found in NIS passwd map"
#define string_unkNisProblem	"dtuser:422" FS "Unknown NIS problem"
#define string_badLogin	"dtuser:423" FS "Cannot change Login ID on NIS conversions"
#define string_groupNotFound		"dtuser:424" FS "%s not found in NIS group map"
#define format_addOwner		"dtuser:425" FS "add ownership to %s?"
#define format_delOwner		"dtuser:426" FS "remove ownership from %s?"

#define format_createUserAcc1	"dtuser:427" FS "you are not authorized to create user accounts"
#define format_createUserAcc2	"dtuser:428" FS "create user account %s?"
#define format_createUserAcc3	"dtuser:429" FS "create user account %s - succeeded"
#define format_createUserAcc4	"dtuser:430" FS "create user account %s - failed"
#define format_createUserAcc5	"dtuser:431" FS "create user account %s - unchanged"

#define format_createDeskEnv1	"dtuser:432" FS "you are not authorized to create desktop environments"
#define format_createDeskEnv2	"dtuser:433" FS "create desktop environment %s?"
#define format_createDeskEnv3	"dtuser:434" FS "create desktop environment %s - succeeded"
#define format_createDeskEnv4	"dtuser:435" FS "create desktop environment %s - failed"
#define format_createDeskEnv5	"dtuser:436" FS "create desktop environment %s - unchanged"

#define format_createGroup1	"dtuser:437" FS "you are not authorized to create groups"
#define format_createGroup2	"dtuser:438" FS "create group %s?"
#define format_createGroup3	"dtuser:439" FS "create group %s - succeeded"
#define format_createGroup4	"dtuser:440" FS "create group %s - failed"
#define format_createGroup5	"dtuser:441" FS "create group %s - unchanged"

#define format_createResAcc1	"dtuser:442" FS "you are not authorized to create reserved accounts"
#define format_createResAcc2	"dtuser:443" FS "create reserved account %s?"
#define format_createResAcc3	"dtuser:444" FS "create reserved account %s - succeeded"
#define format_createResAcc4	"dtuser:445" FS "create reserved account %s - failed"
#define format_createResAcc5	"dtuser:446" FS "create reserved account %s - unchanged"

#define format_modifyUserAcc1	"dtuser:447" FS "you are not authorized to modify user accounts"
#define format_modifyUserAcc2	"dtuser:448" FS "modify user account %s?"
#define format_modifyUserAcc3	"dtuser:449" FS "modify user account %s - succeeded"
#define format_modifyUserAcc4	"dtuser:450" FS "modify user account %s - failed"
#define format_modifyUserAcc5	"dtuser:451" FS "modify user account %s - unchanged"

#define format_modifyDeskEnv1	"dtuser:452" FS "you are not authorized to modify desktop environments"
#define format_modifyDeskEnv2	"dtuser:453" FS "modify desktop environment %s?"
#define format_modifyDeskEnv3	"dtuser:454" FS "modify desktop environment %s - succeeded"
#define format_modifyDeskEnv4	"dtuser:455" FS "modify desktop environment %s - failed"
#define format_modifyDeskEnv5	"dtuser:456" FS "modify desktop environment %s - unchanged"

#define format_modifyGroup1	"dtuser:457" FS "you are not authorized to modify groups"
#define format_modifyGroup2	"dtuser:458" FS "modify group %s?"
#define format_modifyGroup3	"dtuser:459" FS "modify group %s - succeeded"
#define format_modifyGroup4	"dtuser:460" FS "modify group %s - failed"
#define format_modifyGroup5	"dtuser:461" FS "modify group %s - unchanged"

#define format_modifyResAcc1	"dtuser:462" FS "you are not authorized to modify reserved accounts"
#define format_modifyResAcc2	"dtuser:463" FS "modify reserved account %s?"
#define format_modifyResAcc3	"dtuser:464" FS "modify reserved account %s - succeeded"
#define format_modifyResAcc4	"dtuser:465" FS "modify reserved account %s - failed"
#define format_modifyResAcc5	"dtuser:466" FS "modify reserved account %s - unchanged"

#define format_deleteUserAcc1	"dtuser:467" FS "you are not authorized to delete user accounts"
#define format_deleteUserAcc2	"dtuser:468" FS "delete user account %s?"
#define format_deleteUserAcc3	"dtuser:469" FS "delete user account %s - succeeded"
#define format_deleteUserAcc4	"dtuser:470" FS "delete user account %s - failed"
#define format_deleteUserAcc5	"dtuser:471" FS "delete user account %s - unchanged"

#define format_deleteDeskEnv1	"dtuser:472" FS "you are not authorized to delete desktop environments"
#define format_deleteDeskEnv2	"dtuser:473" FS "delete desktop environment %s?"
#define format_deleteDeskEnv3	"dtuser:474" FS "delete desktop environment %s - succeeded"
#define format_deleteDeskEnv4	"dtuser:475" FS "delete desktop environment %s - failed"
#define format_deleteDeskEnv5	"dtuser:476" FS "delete desktop environment %s - unchanged"

#define format_deleteGroup1	"dtuser:477" FS "you are not authorized to delete groups"
#define format_deleteGroup2	"dtuser:478" FS "delete group %s?"
#define format_deleteGroup3	"dtuser:479" FS "delete group %s - succeeded"
#define format_deleteGroup4	"dtuser:480" FS "delete group %s - failed"
#define format_deleteGroup5	"dtuser:481" FS "delete group %s - unchanged"

#define format_deleteResAcc1	"dtuser:482" FS "you are not authorized to delete reserved accounts"
#define format_deleteResAcc2	"dtuser:483" FS "delete reserved account %s?"
#define format_deleteResAcc3	"dtuser:484" FS "delete reserved account %s - succeeded"
#define format_deleteResAcc4	"dtuser:485" FS "delete reserved account %s - failed"
#define format_deleteResAcc5	"dtuser:486" FS "delete reserved account %s - unchanged"

#define format_addOwnerUserAcc1	"dtuser:487" FS "you are not authorized to add ownership to user accounts"
#define format_addOwnerUserAcc2	"dtuser:488" FS "add ownership to user account %s?"
#define format_addOwnerUserAcc3	"dtuser:489" FS "add ownership to user account %s - succeeded"
#define format_addOwnerUserAcc4	"dtuser:490" FS "add ownership to user account %s - failed"
#define format_addOwnerUserAcc5	"dtuser:491" FS "add ownership to user account %s - unchanged"

#define format_addOwnerResAcc1	"dtuser:492" FS "you are not authorized to add ownership to reserved accounts"
#define format_addOwnerResAcc2	"dtuser:493" FS "add ownership to reserved account %s?"
#define format_addOwnerResAcc3	"dtuser:494" FS "add ownership to reserved account %s - succeeded"
#define format_addOwnerResAcc4	"dtuser:495" FS "add ownership to reserved account %s - failed"
#define format_addOwnerResAcc5	"dtuser:496" FS "add ownership to reserved account %s - unchanged"

#define format_delOwnerUserAcc1	"dtuser:497" FS "you are not authorized to remove ownership from user accounts"
#define format_delOwnerUserAcc2	"dtuser:498" FS "remove ownership from user account %s?"
#define format_delOwnerUserAcc3	"dtuser:499" FS "remove ownership from user account %s - succeeded"
#define format_delOwnerUserAcc4	"dtuser:500" FS "remove ownership from user account %s - failed"
#define format_delOwnerUserAcc5	"dtuser:501" FS "remove ownership from user account %s - unchanged"

#define format_delOwnerResAcc1	"dtuser:502" FS "you are not authorized to remove ownership from reserved accounts"
#define format_delOwnerResAcc2	"dtuser:503" FS "remove ownership from reserved account %s?"
#define format_delOwnerResAcc3	"dtuser:504" FS "remove ownership from reserved account %s - succeeded"
#define format_delOwnerResAcc4	"dtuser:505" FS "remove ownership from reserved account %s - failed"
#define format_delOwnerResAcc5	"dtuser:506" FS "remove ownership from reserved account %s - unchanged"
#define format_uidBusyFmt	"dtuser:507" FS "\n\nWarning: Login ID %s is currently logged on. Changing a user's User ID while they are logged on is not recommended because it may cause programs to fail."
#define format_chgUidFmt	"dtuser:508" FS "\n\nYou have selected a new User ID for this account. The User ID of files and folders owned by this account will also be changed so the user can continue to access them. The file /etc/default/usermod controls which files and folders will be changed.  If you want to change different files, click \"No\", edit /etc/default/usermod and then try again."
#define	format_minIdFmt	 	"dtuser:509" FS "Group IDs less than 100 are reserved. You cannot add or modify reserved groups.\n\n"
#define	format_userMinIdFmt 	"dtuser:510" FS "User IDs less than 100 are reserved. You cannot add or modify reserved accounts.\n\n"
