/*	Copyright (c) 1990, 1991, 1992, 1993, 1994 Novell, Inc. All Rights Reserved.	*/
/*	Copyright (c) 1988, 1990 Novell, Inc. All Rights Reserved.	*/
/*	  All Rights Reserved  	*/

/*	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF Novell Inc.	*/
/*	The copyright notice above does not evidence any   	*/
/*	actual or intended publication of such source code.	*/

#ifndef Language_h
#define Language_h
#ident	"@(#)debugger:inc/common/Language.h	1.5"

enum Language {
    UnSpec,	// unspecified, use current default
    C,		// debug C exprs.
    CPLUS,	// debug full C++ expressions, C++ lang attribute found in DWARF record
    CPLUS_ASSUMED, // debug C++ subset, C++ assumed from presence of __cpp_version_302
		   // variable generated by cfront
    CPLUS_ASSUMED_V2, // debug C++ subset, assumed from presence of __cpp_unixware_20
		      // variable generated by C-generating back end of ANSI C++ compiler
};

class ProcObj;

Language	current_language(ProcObj *pobj = 0);
		// This routine arbitrates the value between %lang and %db_lang
const char	*language_name(Language);
int	 	set_language(const char *);
		// This routine sets the %lang value.
Language	current_context_language(ProcObj *pobj = 0);
		// This routine gets the %db_lang value.
Language	current_user_language();
		// This routine gets the %lang value.

#endif /*Language_h*/
