/*ident	"@(#)G2++:incl/g2mach.h	3.0"  */
/******************************************************************************
*
* C++ Standard Components, Release 3.0.
*
* Copyright (c) 1991, 1992 AT&T and Unix System Laboratories, Inc.
* Copyright (c) 1988, 1989, 1990 AT&T.  All Rights Reserved.
*
* THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T and Unix System
* Laboratories, Inc.  The copyright notice above does not evidence
* any actual or intended publication of such source code.
*
******************************************************************************/

//
// G2 machine-dependent parameters
// (this file is generated by the program geng2mach;
// it should NOT be on a distribution tape)
//
#ifndef G2MACHH
#define G2MACHH

const int CHAR_SIZE_ATTLC=1;
const int SHORT_SIZE_ATTLC=2;
const int LONG_SIZE_ATTLC=4;
const int STRING_SIZE_ATTLC=4;
const int VBLOCK_SIZE_ATTLC=12;

const int CHAR_ALIGN_ATTLC=1;
const int SHORT_ALIGN_ATTLC=2;
const int LONG_ALIGN_ATTLC=4;
const int STRING_ALIGN_ATTLC=4;
const int VBLOCK_ALIGN_ATTLC=4;
const int STRUCT_ALIGN_ATTLC=1;

#endif
