#	Copyright (c) 1990, 1991, 1992, 1993, 1994 Novell, Inc. All Rights Reserved.
#	Copyright (c) 1984, 1985, 1986, 1987, 1988, 1989, 1990 Novell, Inc. All Rights Reserved.
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF Novell Inc.
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.


#ident	"@(#)expr:expr.mk	1.9.6.6"
#ident "$Header: expr.mk 1.3 91/08/13 $"

#	Makefile for expr

include $(CMDRULES)

INSDIR = $(USRBIN)
OWN = bin
GRP = bin

LDLIBS = -lgen

#top#
# Generated by makefile 1.47

MAKEFILE = expr.mk

MAINS = expr expr.dy

OBJECTS =  expr.o expres.o

SOURCES =  expr.c expres.c

all:		$(MAINS)

expr:		$(OBJECTS)
	$(CC) -o $@ $(OBJECTS) $(LDFLAGS) $(LDLIBS) $(NOSHLIBS)

expr.dy:	$(OBJECTS)
	$(CC) -o $@ $(OBJECTS) $(LDFLAGS) $(LDLIBS) $(SHLIBS)

expr.o: expr.c \
	$(INC)/stdlib.h \
	$(INC)/regexpr.h \
	$(INC)/locale.h \
	$(INC)/pfmt.h \
	expr.h

expres.o: expres.c \
	expr.h

install: expr expr.dy
	$(INS) -f $(SBIN) -m 0555 -u $(OWN) -g $(GRP) expr
	$(INS) -f $(USRBIN) -m 0555 -u $(OWN) -g $(GRP) expr.dy
	-/bin/mv $(USRBIN)/expr.dy $(USRBIN)/expr

clean:
	rm -f $(OBJECTS)

clobber: clean
	rm -f $(MAINS)

lintit:
	$(LINT) $(LINTFLAGS) $(SOURCES)

#	These targets are useful but optional

partslist:
	@echo $(MAKEFILE) $(SOURCES) $(LOCALINCS)  |  tr ' ' '\012'  |  sort

productdir:
	@echo $(INSDIR) | tr ' ' '\012' | sort

product:
	@echo $(MAINS)  |  tr ' ' '\012'  | \
	sed 's;^;$(INSDIR)/;'

srcaudit:
	@fileaudit $(MAKEFILE) $(LOCALINCS) $(SOURCES) -o $(OBJECTS) $(MAINS)
