#	Copyright (c) 1990, 1991, 1992, 1993, 1994 Novell, Inc. All Rights Reserved.
#	Copyright (c) 1984, 1985, 1986, 1987, 1988, 1989, 1990 Novell, Inc. All Rights Reserved.
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF Novell Inc.
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.


#ident	"@(#)ksh:ksh.mk	1.8.12.3"
#ident  "$Header: ksh.mk 1.3 91/06/27 $"

include $(CMDRULES)

# makefile for ksh generated by mkold and hand modified

OWN = bin
GRP = root

# for RDS: set INSDIR = $(USRLBIN)/usr/lbin, else $(USRBIN)
INSDIR = $(USRBIN)

all: ksh

ksh: 
	cd shlib; $(MAKE) $(MAKEARGS) -f shlib.mk all
	cd sh;    $(MAKE) $(MAKEARGS) -f sh.mk all

install: all
	-rm -f $(INSDIR)/ksh
	 $(INS) -o -m 0555 -u $(OWN) -g $(GRP) -f $(INSDIR) sh/ksh
	$(CH)-rm -f $(INSDIR)/rksh
	$(CH)-ln -f $(INSDIR)/ksh $(INSDIR)/rksh

clean:
	cd shlib; $(MAKE) $(MAKEARGS) -f shlib.mk $@
	cd sh;    $(MAKE) $(MAKEARGS) -f sh.mk $@

clobber: clean
	cd shlib; $(MAKE) $(MAKEARGS) -f shlib.mk $@
	cd sh;    $(MAKE) $(MAKEARGS) -f sh.mk $@

lintit:
	cd shlib; $(MAKE) $(MAKEARGS) -f shlib.mk $@
	cd sh;    $(MAKE) $(MAKEARGS) -f sh.mk $@
