1 Errore
2 Attendere
3 Ricerca nella libreria...
4 Impossibile avviare Library Browser, potrebbe non essere stato installato.
5 Collegamento di guida costruito impropriamente.
6 Debug: Specificata un'opzione della riga di comandi non valida.
7 Collegamento di guida costruito impropriamente: troppi argomenti.
8 Il libro %s non è installato nel sistema.
9 Manca il permesso di leggere il libro %s.
10 Il capitolo e il paragrafo indicato non sono stati trovati nella libreria.
11 Impossibile leggere un file di dati interno del browser di libreria.
12 Impossibile aprire il library browser principale.
13 Errore interno di programma: impossibile inizializzare la funzione callback.
14 Il browser di documenti non è installato nel sistema.
15 Impossibile trovare la collezione di libri %s.
