1 Fehler
2 Bitte warten
3 Bibliothek wird durchsucht...
4 Der Browser für die Bibliothek kann nicht gestartet werden, er ist unter Umständen nicht installiert.
5 Falsch konstruierte Hilfeverknüpfung.
6 Debug: Ungültige Befehlszeilenoption angegeben.
7 Falsch konstruierte Hilfeverknüpfung: zuviele Argumente.
8 Das Buch %s ist nicht auf Ihrem System installiert.
9 Sie sind nicht berechtigt, das Buch %s zu lesen.
10 Referenziertes Kapitel und Abschnitt können in der Bibliothek nicht gefunden werden.
11 Eine interne Datendatei des Bibliothek-Browsers kann nicht gelesen werden.
12 Der Hauptbibliothek-Browser kann nicht geöffnet werden.
13 Interner Programmfehler: Rückruffunktion kann nicht initialisiert werden.
14 Der Dokumentations-Browser wurde auf Ihrem System nicht installiert.
15 Die %s-Reihe von Büchern kann nicht gefunden werden
