#!/usr/bin/perl

# $Header: /SRCS/esmp/usr/src/nw/cmd/gnu/perl-4.036/eg/scan/scan_passwd,v 1.1.1.1 1993/10/11 20:26:20 ram Exp $

# This scans passwd file for security holes.

open(Pass,'/etc/passwd') || die "Can't open passwd file: $!\n";
# $dotriv = (`date` =~ /^Mon/);
$dotriv = 1;

while (<Pass>) {
    ($login,$pass,$uid,$gid,$gcos,$home,$shell) = split(/:/);
    if ($shell eq '') {
	print "Short: $_";
    }
    next if /^[+]/;
    if ($pass eq '') {
	if (index(":sync:lpq:+:", ":$login:") < 0) {
	    print "No pass: $login\t$gcos\n";
	}
    }
    elsif ($dotriv && crypt($login,substr($pass,0,2)) eq $pass) {
	print "Trivial: $login\t$gcos\n";
    }
    if ($uid == 0) {
	if ($login !~ /^.?root$/ && $pass ne '*') {
	    print "Extra root: $_";
	}
    }
}
